# Generated by Django 4.1.2 on 2022-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='names',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_prefix',
            field=models.CharField(choices=[('+56', '+56'), ('+54', '+54')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='second_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_adress',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
