# Generated by Django 4.1 on 2022-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_contact_names_contact_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.TextField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='productos_img')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_adress',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
