# Generated by Django 4.1 on 2022-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_alter_contact_email_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.CharField(default='', max_length=9),
        ),
    ]
